default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gaffer_development
  username: postgres
  password: Hqex8TyiUjRTKDQ

test:
  <<: *default
  database: gaffer_test
  username: postgres
  password: Hqex8TyiUjRTKDQ

production:
  <<: *default
  database: gaffer_production
