require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GameWeeksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GameWeek. As you add validations to GameWeek, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GameWeeksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all game_weeks as @game_weeks" do
      game_week = GameWeek.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:game_weeks)).to eq([game_week])
    end
  end

  describe "GET show" do
    it "assigns the requested game_week as @game_week" do
      game_week = GameWeek.create! valid_attributes
      get :show, {:id => game_week.to_param}, valid_session
      expect(assigns(:game_week)).to eq(game_week)
    end
  end

  describe "GET edit" do
    it "assigns the requested game_week as @game_week" do
      game_week = GameWeek.create! valid_attributes
      get :edit, {:id => game_week.to_param}, valid_session
      expect(assigns(:game_week)).to eq(game_week)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GameWeek" do
        expect {
          post :create, {:game_week => valid_attributes}, valid_session
        }.to change(GameWeek, :count).by(1)
      end

      it "assigns a newly created game_week as @game_week" do
        post :create, {:game_week => valid_attributes}, valid_session
        expect(assigns(:game_week)).to be_a(GameWeek)
        expect(assigns(:game_week)).to be_persisted
      end

      it "redirects to the created game_week" do
        post :create, {:game_week => valid_attributes}, valid_session
        expect(response).to redirect_to(GameWeek.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved game_week as @game_week" do
        post :create, {:game_week => invalid_attributes}, valid_session
        expect(assigns(:game_week)).to be_a_new(GameWeek)
      end

      it "re-renders the 'new' template" do
        post :create, {:game_week => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested game_week" do
        game_week = GameWeek.create! valid_attributes
        put :update, {:id => game_week.to_param, :game_week => new_attributes}, valid_session
        game_week.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested game_week as @game_week" do
        game_week = GameWeek.create! valid_attributes
        put :update, {:id => game_week.to_param, :game_week => valid_attributes}, valid_session
        expect(assigns(:game_week)).to eq(game_week)
      end

      it "redirects to the game_week" do
        game_week = GameWeek.create! valid_attributes
        put :update, {:id => game_week.to_param, :game_week => valid_attributes}, valid_session
        expect(response).to redirect_to(game_week)
      end
    end

    describe "with invalid params" do
      it "assigns the game_week as @game_week" do
        game_week = GameWeek.create! valid_attributes
        put :update, {:id => game_week.to_param, :game_week => invalid_attributes}, valid_session
        expect(assigns(:game_week)).to eq(game_week)
      end

      it "re-renders the 'edit' template" do
        game_week = GameWeek.create! valid_attributes
        put :update, {:id => game_week.to_param, :game_week => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested game_week" do
      game_week = GameWeek.create! valid_attributes
      expect {
        delete :destroy, {:id => game_week.to_param}, valid_session
      }.to change(GameWeek, :count).by(-1)
    end

    it "redirects to the game_weeks list" do
      game_week = GameWeek.create! valid_attributes
      delete :destroy, {:id => game_week.to_param}, valid_session
      expect(response).to redirect_to(game_weeks_url)
    end
  end

end
