require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeamsController do

  # This should return the minimal set of attributes required to create a valid
  # Team. As you add validations to Team, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeamsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let!(:user) { create(:user) }

  before do
    sign_in(user)
  end

  describe "GET index" do
    context "logged in" do
      it "assigns all teams as @teams" do
        team = user.teams.create! valid_attributes
        get :index, {}, valid_session
        assigns(:teams).should eq([team])
        expect(assigns(:teams).map(&:user)).to eq([user])
      end

      it "does not load other user's teams" do
        other_team = Team.create!(valid_attributes.merge(user_id: create(:user).id))
        get :index, {}, valid_session
        expect(assigns(:teams)).to_not include(other_team)
      end

    end
  end

  describe "GET show" do
    it "assigns the requested team as @team for the logged in user" do
      team = user.teams.create! valid_attributes
      get :show, {:id => team.to_param}, valid_session
      assigns(:team).should eq(team)
      expect(assigns(:team).user).to eq(user)
    end
  end

  describe "GET new" do
    it "assigns a new team as @team for the logged in user" do
      get :new, {}, valid_session
      assigns(:team).should be_a_new(Team)
      expect(assigns(:team).user).to eq(user)
    end
  end

  describe "GET edit" do
    it "assigns the requested team as @team" do
      team = user.teams.create! valid_attributes
      get :edit, {:id => team.to_param}, valid_session
      assigns(:team).should eq(team)
      expect(assigns(:team).user).to eq(user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Team" do
        expect {
          post :create, {:team => valid_attributes}, valid_session
        }.to change(Team, :count).by(1)
      end

      it "assigns a newly created team as @team" do
        post :create, {:team => valid_attributes}, valid_session
        assigns(:team).should be_a(Team)
        assigns(:team).should be_persisted
      end

      it "redirects to the created team" do
        post :create, {:team => valid_attributes}, valid_session
        response.should redirect_to(Team.last)
      end

      it "create a team for the current user" do
        post :create, {:team => valid_attributes}, valid_session
        team = Team.last
        expect(team.user).to eq(user)
      end

      it "does not allow users to create teams for other users" do
        other_user = create(:user)
        post :create, {:team => valid_attributes.merge(user_id: other_user.id)}, valid_session
        team = Team.last
        expect(team.user).to eq(user)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved team as @team" do
        Team.any_instance.stub(:save).and_return(false)
        post :create, {:team => { "title" => "invalid value" }}, valid_session
        assigns(:team).should be_a_new(Team)
      end

      it "re-renders the 'new' template" do
        Team.any_instance.stub(:save).and_return(false)
        post :create, {:team => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested team" do
        team = user.teams.create! valid_attributes
        # Assuming there are no other teams in the database, this
        # specifies that the Team created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Team.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => team.to_param, :team => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested team as @team" do
        team = user.teams.create! valid_attributes
        put :update, {:id => team.to_param, :team => valid_attributes}, valid_session
        assigns(:team).should eq(team)
      end

      it "redirects to the team" do
        team = user.teams.create! valid_attributes
        put :update, {:id => team.to_param, :team => valid_attributes}, valid_session
        response.should redirect_to(team)
      end
    end

    describe "with invalid params" do
      it "assigns the team as @team" do
        team = user.teams.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Team.any_instance.stub(:save).and_return(false)
        put :update, {:id => team.to_param, :team => { "title" => "invalid value" }}, valid_session
        assigns(:team).should eq(team)
      end

      it "re-renders the 'edit' template" do
        team = user.teams.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Team.any_instance.stub(:save).and_return(false)
        put :update, {:id => team.to_param, :team => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested team" do
      team = user.teams.create! valid_attributes
      expect {
        delete :destroy, {:id => team.to_param}, valid_session
      }.to change(Team, :count).by(-1)
    end

    it "redirects to the teams list" do
      team = user.teams.create! valid_attributes
      delete :destroy, {:id => team.to_param}, valid_session
      response.should redirect_to(teams_url)
    end
  end
end
